services:

  app:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    container_name: django
    expose:
      - "8000"
    command: sh -c "/code/entrypoint.sh"
    volumes:
      - .:/code
      - static:/static
    env_file:
      - .env.http

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx-http.conf:/etc/nginx/conf.d/default.conf
      - ./html:/var/www/html
      - static:/static
    depends_on:
      - app

volumes:
  static:
    
