services:
  app:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    container_name: django
    expose:
      - "8000"
    command: sh -c "/code/entrypoint.sh"
    volumes:
      - .:/code
      - ./static:/static
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./html:/var/www/html
      - ./static:/static
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./html:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    command: ["--version"]

